version: '3.7'

services:
  database:
    container_name: perusable-database
    image: postgres:12.1
    ports:
      - 5433:5432
    volumes:
      - perusable-database:/var/lib/postgresql/data

  elasticsearch:
    container_name: perusable-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    image: elasticsearch:7.5.0
    ports:
      - 9201:9200
    volumes:
      - perusable-elasticsearch:/usr/share/elasticsearch/data

  server:
    build:
      context: ./server
    container_name: perusable-server
    command: [ "bash", "start.sh" ]
    depends_on:
      - database
      - elasticsearch
    environment:
      - PGDATABASE=perusable
      - PGUSER=perusable
      - PGPASSWORD=perusable
      - PGHOST=perusable-database
      - ES_HOSTS=http://perusable-elasticsearch:9200
    ports:
      - 8001:8000
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/app/static

  client:
    build:
      context: ./client
    command: [ "npm", "start" ]
    container_name: perusable-client
    depends_on:
      - server
    ports:
      - 3001:3000

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: perusable-reverse-proxy
    depends_on:
      - server
      - client
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/usr/src/app/static

volumes:
  perusable-database:
  perusable-elasticsearch:
  static: